export const ACTIONS = {
  TICK: 'TICK',
  EAT_CANDY: 'EAT_CANDY',
  BUY_MERCHANT_ITEM: 'BUY_MERCHANT_ITEM',
  TAKE_DAMAGE: 'TAKE_DAMAGE',
  CLICK_MERCHANT_HAT: 'CLICK_MERCHANT_HAT',
  CLEAR_MERCHANT_HAT_MESSAGE: 'CLEAR_MERCHANT_HAT_MESSAGE',
}
