export const ACTIONS = {
  TICK: 'TICK',
  EAT_CANDY: 'EAT_CANDY',
  BUY_MERCHANT_ITEM: 'BUY_MERCHANT_ITEM',
  TAKE_DAMAGE: 'TAKE_DAMAGE',
  CLICK_MERCHANT_HAT: 'CLICK_MERCHANT_HAT',
  CLICK_MERCHANT_STICK: 'CLICK_MERCHANT_STICK',
  CLEAR_MERCHANT_DIALOG: 'CLEAR_MERCHANT_DIALOG',
  ASK_MERCHANT_WHERE_AM_I: 'ASK_MERCHANT_WHERE_AM_I',
  CLICK_MERCHANT_MAP: 'CLICK_MERCHANT_MAP',
  LOAD_GAME_STATE: 'LOAD_GAME_STATE',
  RESET_GAME: 'RESET_GAME',
}
