export const initialState = {
  candies: 0,
  candiesEaten: 0,
  candiesPerSecond: 1,
  merchantAppeared: false,
  lollipops: 0,
  characterDisplayUnlocked: false,
  menuUnlocked: false,
  mapUnlocked: false,
  merchantWhereAmIAsked: false,
  merchantMapOfferActive: false,
  merchantMapOfferDialogVisible: false,
  merchantMapPrice: 500,
  merchantMapClickCount: 0,
  merchantMapMessageIndex: null,
  currentHp: 100,
  merchantHatClickCount: 0,
  merchantHatMessageIndex: null,
  merchantLollipopPrice: 100,
  merchantStickOfferVisible: false,
  merchantWalkingStickOwned: false,
  equipment: {
    weapon: null,
    chest: null,
    feet: null,
    hands: null,
    head: null,
  },
}
