export const initialState = {
  candies: 0,
  candiesEaten: 0,
  candiesPerSecond: 1,
  merchantAppeared: false,
  lollipops: 0,
  characterDisplayUnlocked: false,
  menuUnlocked: false,
  currentHp: 100,
  merchantHatClickCount: 0,
  merchantHatMessageIndex: null,
  merchantLollipopPrice: 100,
  equipment: {
    weapon: null,
    chest: null,
    feet: null,
    hands: null,
    head: null,
  },
}
